version: '3.8'

services:
  # NameServer服务
  namesrv:
    image: ${ROCKETMQ_IMAGE:-apache/rocketmq:4.9.7}
    container_name: rocketmq-namesrv
    ports:
      - "${NAMESRV_HOST_PORT:-19876}:${NAMESRV_CONTAINER_PORT:-9876}"
    volumes:
      - ${HOST_LOG_NAMESRV:-/data/rocketmq-4.9.7-docker/log/namesrv}:/root/logs
      - ${HOST_DATA_NAMESRV:-/data/rocketmq-4.9.7-docker/data/namesrv}:/root/store
    command: sh mqnamesrv
    networks:
      - rocketmq-net
    restart: unless-stopped
  
  # Broker服务
  broker:
    image: ${ROCKETMQ_IMAGE:-apache/rocketmq:4.9.7}
    container_name: rocketmq-broker
    ports:
      - "${BROKER_PORT1_HOST:-20911}:${BROKER_PORT1_CONTAINER:-20911}"
      - "${BROKER_PORT2_HOST:-20912}:${BROKER_PORT2_CONTAINER:-20912}"
      - "${BROKER_PORT3_HOST:-20913}:${BROKER_PORT3_CONTAINER:-20913}"
    volumes:
      - ${HOST_LOG_BROKER:-/data/rocketmq-4.9.7-docker/log/broker}:/root/logs
      - ${HOST_DATA_BROKER:-/data/rocketmq-4.9.7-docker/data/broker}:/root/store
      - ${BROKER_CONF:-../rocketmq-conf/docker/broker.conf}:/opt/rocketmq-4.9.7/conf/broker.conf
      - ${ACL_CONF:-../rocketmq-conf/docker/plain-acl.conf}:/opt/rocketmq-4.9.7/conf/plain-acl.conf
    environment:
      - NAMESRV_ADDR=${NAMESRV_ADDR_IN_BROKER:-namesrv:9876}
    command: sh mqbroker -c /opt/rocketmq-4.9.7/conf/broker.conf
    depends_on:
      - namesrv
    networks:
      - rocketmq-net
    restart: unless-stopped

networks:
  rocketmq-net:
    driver: bridge